### ISSUE TITLE
Error: Cannot find module 'depd'

### ISSUE THREAD

**Issue by marchant** [jonniespratley/jps-passbook-manager#1]
When cloning the repo, wether using the committed node_modules or doing npm install again, I get this when doing:

node server

( node v0.10.33)

module.js:340
    throw err;
          ^
Error: Cannot find module 'depd'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/benoit/Sites/jonniespratley/jps-passbook-manager/node_modules/express/lib/express.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by jonniespratley** [comment]
I will look into the dependencies and fix.

**Comment by GemsKnight** [comment]
How did you fix it ? I have the same error with my owns project (depd is installed but I've got the same error)
